version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    image: ccp/frontend
    ports:
      - '2424:2424'

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    image: ccp/backend
    ports:
      - '4848:4848'
