version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    image: ccp/frontend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ccp-frontend.rule=Host(`ccp.redcouch.at`)'
      - 'traefik.http.routers.ccp-frontend.entrypoints=websecure'
      - 'traefik.http.routers.ccp-frontend.tls.certresolver=myresolver'
    networks:
      internal:
    restart: always
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    image: ccp/backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ccp-backend.rule=Host(`ccp.backend.redcouch.at`)'
      - 'traefik.http.routers.ccp-backend.entrypoints=websecure'
      - 'traefik.http.routers.ccp-backend.tls.certresolver=myresolver'
    networks:
      internal:
    restart: always
networks:
  internal:
    external:
      name: paddy_internal
